#!/bin/sh
# Regenerates the point-by-point OPD comparison in this folder from the gathered results in
# tests/TestData. Run from the repository root:  sh docs/opd/compare/generate.sh
# Each file holds, for one lens and one ray-aiming mode, every program's OPD with respect to the
# chief ray at the 857 OPDC points beside WEC's W, one table per field.
set -e
dotnet build src/WavefrontErrorCalculator.Cli -c Debug -v q -nologo > /dev/null
wfe="dotnet src/WavefrontErrorCalculator.Cli/bin/Debug/net8.0/wfe.dll"
d=tests/TestData
out=docs/opd/compare
common="--set ChiefRay=StopCenter --set PupilOrientation=EntrancePupilPlane --values"
for lens in KingslakeDG Cooke_40deg_FC US8264785_Ex4 Relay_1to1 Objective_NA03_5x; do
  # Every program on the same refractive indices, Zemax's (the AGF catalogs): Optiland traced on
  # them (verification/optiland/points.py --indices), and LensHH-LT's double Gauss gathered with
  # only the Schott catalog, since the file names F4 with no catalog. OSLO's already match.
  lh=""; [ "$lens" = KingslakeDG ] && lh=_Schott
  $wfe opd-table "$d/$lens.zmx" \
    "Zemax=$d/zemax-opdc/${lens}_OPDC_Off.json" \
    "LensHH-LT=$d/lenshh-lt-opdc/${lens}_OPDC_Off${lh}.json" \
    "Optiland=$d/optiland-opdc/${lens}_OPDC_ZemaxIndices.json" \
    "OSLO enp=$d/oslo-opdc/${lens}_OPDC_enp.json" \
    "OSLO crr=$d/oslo-opdc/${lens}_OPDC_crr.json" \
    --set RayAiming=Paraxial $common --out "$out/${lens}_AimingOff.md"
  $wfe opd-table "$d/$lens.zmx" \
    "Zemax=$d/zemax-opdc/${lens}_OPDC_Real.json" \
    "LensHH-LT=$d/lenshh-lt-opdc/${lens}_OPDC_Real${lh}.json" \
    --set RayAiming=RealStop $common --out "$out/${lens}_AimingReal.md"
done

# LensHH-LT against OpticStudio directly, ray by ray, at all three wavelengths.
dd="node $out/direct_diff.js $d"
{
  echo '# LensHH-LT against OpticStudio, ray by ray'
  echo
  echo 'Generated by `docs/opd/compare/generate.sh`. Largest |LensHH-LT − OpticStudio| OPDC in waves,'
  echo 'over the 857 points at all three wavelengths, counting only rays both programs trace.'
  echo 'The double Gauss compares LensHH-LT gathered with only the Schott catalog (`*_Schott.json`),'
  echo 'so that its F4 is the one OpticStudio takes.'
  echo
  $dd lenshh-lt-opdc _Schott KingslakeDG
  $dd lenshh-lt-opdc '' Cooke_40deg_FC,US8264785_Ex4,Relay_1to1,Objective_NA03_5x | tail -n +3
} > "$out/LensHH-LT_vs_OpticStudio.md"
echo "wrote $out/LensHH-LT_vs_OpticStudio.md"
