<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WavefrontErrorCalculator.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WavefrontErrorCalculator.Core\WavefrontErrorCalculator.Core.csproj" />
    <ProjectReference Include="..\..\src\WavefrontErrorCalculator.Cli\WavefrontErrorCalculator.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\TestData\**\*" CopyToOutputDirectory="PreserveNewest" LinkBase="TestData" />
    <None Include="..\..\external\AberrationCalculator\catalogs\**\*" CopyToOutputDirectory="PreserveNewest" LinkBase="catalogs" />
  </ItemGroup>
</Project>
